<a href="https://colab.research.google.com/github/Thakurkorea/ASF_wild_boar/blob/main/SDC_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install sodapy

In [14]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
# pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cdc.gov", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.cdc.gov,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("ijqb-a7ye", limit=5000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)
print(np.shape(results_df))
results_df.tail()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

(5000, 11)

,vaccine,dose,geography_type,geography,year_season,coverage_estimate,population_sample_size,percent_surveyed,foot_notes,survey_type,number_of_exemptions
4995,Exemption,Any Exemption,States,Nevada,2010-11,NA,NaN,NaN,NaN,NA,NaN
4996,Exemption,Any Exemption,States,New Hampshire,2010-11,NA,NaN,NaN,NaN,NA,NaN
4997,Exemption,Any Exemption,States,New Jersey,2010-11,NA,NaN,NaN,NaN,NA,NaN
4998,Exemption,Any Exemption,States,New Mexico,2010-11,NA,NaN,NaN,NaN,NA,NaN
4999,Exemption,Any Exemption,States,New York,2010-11,NA,NaN,NaN,NaN,NA,NaN

In [11]:
import numpy as np
np.shape(results_df)

(2000, 11)